id: YNaLgQCZmsk
src: youtube
title: CPANFile
speaker: tatsuhiko-miyagawa
source: london-perl-workshop-2011
view_count: 14
favorite_count: 0
length: 05:33
date: 2011-11-12
format: markdown

__DESCRIPTION__

Recorded at the London Perl Workshop 2011
